### ISSUE TITLE
how to use?

### ISSUE THREAD

**Issue by qing8888** [haze/nocap#2]
What is the params?
 
```POST http://abc/recognize```

```
{
    image:'base64 data'
}
```

or other?

Thanks

**Comment by haze** [comment]
you can ingest an image by uploading the raw bytes, or the base64 encoded version, whichever is easier in your language. You have to specify the `image_kind` though, and send it along in the `content` field. Like this:

```json
{
    "challenge": "bus",
    "image_kind": "base64", // or` bytes`
    "content": ...
}
```

**Comment by qing8888** [comment]
Maybe:
```
{
    "challenge": "bus",
    "image_type": "base64", // or "bytes"
    "content": ...
}
```
is right?

**Comment by qing8888** [comment]
{
    "challenge": "bus",
    "image_type": "base64", // or "bytes"
    "image": ""
}

**Comment by qing8888** [comment]
```
{
    "Ok": {
        "affirmative_confidence": 0.34013772,
        "negative_confidence": 0.65986234
    }
}
```
How to know the specific identification results?

**Comment by haze** [comment]
With reCaptcha v2 in mind, you're given the challenge payload, and images. You are supposed to upload the each of the 3x3 images with the given challenge to receive a confidence. It is up to you to determine whether or not the image is one you should click on and submit. You can have it be as simple as just checking if the affirmative confidence is more than 50%, and the negative is less than 45%.

**Comment by qing8888** [comment]
Thanks a lot.Maybe i can know which block i should click.What should i do for this function?



发自我的iPhone


------------------ Original ------------------
From: haze ***@***.***&gt;
Date: Wed,Jun 2,2021 2:18 AM
To: haze/nocap ***@***.***&gt;
Cc: Qing ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [haze/nocap] how to use? (#2)





 
With reCaptcha v2 in mind, you're given the challenge payload, and images. You are supposed to upload the each of the 3x3 images with the given challenge to receive a confidence. It is up to you to determine whether or not the image is one you should click on and submit. You can have it be as simple as just checking if the affirmative confidence is more than 50%, and the negative is less than 45%.

**Comment by haze** [comment]
模仿浏览器点击你认为正确的每张图片

**Comment by qing8888** [comment]
哈哈，大大。

**Comment by qing8888** [comment]
目前来看，还需要知道哪几张图片是正确的。您这个只是判断辨识率吗？

**Comment by haze** [comment]
这只是一个训练有素的机器学习模型，为图像的每个部分提供一个 "信心 "分数。响应会告诉你是否应该点击它。

**Comment by qing8888** [comment]
明白，就是说我把每个图像都判断一次，看看是否需要点击，就能知道最终结果了

**Comment by qing8888** [comment]
刚接触这块，单纯编译tensorflow-sys都踩了很多坑，哈哈哈。我是否能在您的基础上再次训练这个模型呢？

**Comment by haze** [comment]
你可以
